.\" Copyright Amazon.com Inc. or its affiliates. All Rights Reserved.
.\"
.\" This work is licensed under the Creative Commons
 \" Attribution-ShareAlike 4.0 International License. To view a copy
 \" of this license, visit
 \" http://creativecommons.org/licenses/by-sa/4.0/.
 \" SPDX-License-Identifier: CC-BY-SA-4.0
.TH EBSNVME-ID 8 "Jan 19 2024"
.SH NAME
ebsnvme-id \- Reads and prints EBS information from NVMe devices
.SH SYNOPSIS
.B ebsnvme-id
.RI [ options ]
.br
.SH DESCRIPTION
.B ebsnvme-id
uses the NVMe Management Interface to read various metadata about
NVMe-attached EBS storage volumes.  It can be used to retrive the EBS
Volume ID or EC2 API device mapping value given the local block device
name.

.SH OPTIONS
.TP
.B \-v <device>
Return volume-id
.TP
.B \-b <device>, \-u <device>
Return block device mapping (\-u is a deprecated alias)
.TP
.B \-U <device>
Output data for the device as udev environment environment variables
suitable for use with
.B IMPORT{program}
in a udev rule
.TP
.B \-h
Show summary of options.
.SH SEE ALSO
.BR nvme (1),
.BR ec2-metadata (1).
.PP
The storage chapter of the Amazon EC2 User Guide
.br
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/Storage.html
